export const palettes = [
  ['#154255', '#FAEBD7', '#f3bc17', '#FAEBD7', '#dcdcdc', '#c0504f', '#68b9b0', '#FAEBD7', '#2763ab', '#FAEBD7'],
  ['#FAEBD7', '#FAEBD7', '#FAEBD7', '#FAEBD7', '#FAEBD7', '#FAEBD7', '#FAEBD7', '#FAEBD7', '#FAEBD7', '#FAEBD7'],
  ['#FAEBD7', '#9dcee2', '#f29479', '#FAEBD7', '#f29479', '#FAEBD7', '#edf6f9', '#FAEBD7', '#9dcee2', '#FAEBD7'],
  ['#dfde80', '#FAEBD7', '#8c6677', '#ad7787', '#FAEBD7', '#FAEBD7', '#FAEBD7', '#f078b3', '#ec8782', '#dfde80'],
  ['#dad7cd', '#FAEBD7', '#588157', '#3a5a40', '#a3b18a', '#FAEBD7', '#dad7cd', '#FF9D47', '#3a5a40', '#FAEBD7'],
  ['#ff9483', '#fca986', '#f8bd88', '#f0e68c', '#f4eda9', '#f8f3c6', '#ffffff', '#ffe286', '#ffd349', '#ffc40c'],
  ['#ff0a54', '#ff477e', '#ff5c8a', '#ff7096', '#f7cad0', '#ff85a1', '#ff99ac', '#fbb1bd', '#f9bec7', '#fae0e4'],
  ['#71093b', '#990b52', '#cb8b15', '#eaaa34', '#f1f4f9', '#ffffff', '#749ed2', '#467ec3', '#023578', '#022450'],
]

export enum ColorStyle {
  White = 'white',
  LightGray = 'lightGray',
  Gray = 'gray',
  Black = 'black',
  Green = 'green',
  Cyan = 'cyan',
  Blue = 'blue',
  Indigo = 'indigo',
  Violet = 'violet',
  Red = 'red',
  Orange = 'orange',
  Yellow = 'yellow',
}

export enum StickyNoteColorStyle {
  backgroundColor = '#ffc078',
}

export enum SizeStyle {
  Small = 'small',
  Medium = 'medium',
  Large = 'large',
}

export enum DrawerSetting {
  Width = 480,
}

export enum UnsplashSetting {
  ApplicationName = 'what-is-my-new-tab',
  AccessKey = 'KM1kMtcaYX2SZQR1m_o-pwg4RJZUVivPZgfJsbw5h2o',
  SecretKey = 'ma572d0k1fKQIBlLm49h9k3A7np9X_ezS1hfu4Upaeo',
}

export enum FontFamily {
  DEFAULT = 'DEFAULT',
  LXGW = 'LXGW WenKai',
  KuaiLe = 'ZCOOL KuaiLe',
  XiaoWei = 'ZCOOL XiaoWei',
}

export enum Animatiss {
  // SCALE UP
  'scaleUpCenter' = 'scale-up-center',
  'scaleUpTop' = 'scale-up-top',
  'scaleUpBottom' = 'scale-up-bottom',
  'scaleUpLeft' = 'scale-up-left',
  'scaleUpRight' = 'scale-up-right',
  'scaleUpBottomLeft' = 'scale-up-bottom-left',
  'scaleUpBottomRight' = 'scale-up-bottom-right',
  'scaleUpTopLeft' = 'scale-up-top-left',
  'scaleUpTopRight' = 'scale-up-top-right',
  'scaleUpVerticalCenter' = 'scale-up-vertical-center',
  'scaleUpHorizontalCenter' = 'scale-up-horizontal-center',
  'scaleUpVerticalTop' = 'scale-up-vertical-top',
  'scaleUpVerticalBottom' = 'scale-up-vertical-bottom',
  'scaleUpHorizontalLeft' = 'scale-up-horizontal-left',
  'scaleUpHorizontalRight' = 'scale-up-horizontal-right',
  // SCALE DOWN
  'scaleDownCenter' = 'scale-down-center',
  'scaleDownTop' = 'scale-down-top',
  'scaleDownBottom' = 'scale-down-bottom',
  'scaleDownLeft' = 'scale-down-left',
  'scaleDownRight' = 'scale-down-right',
  'scaleDownBottomLeft' = 'scale-down-bottom-left',
  'scaleDownBottomRight' = 'scale-down-bottom-right',
  'scaleDownTopLeft' = 'scale-down-top-left',
  'scaleDownTopRight' = 'scale-down-top-right',
  'scaleDownHorizontalCenter' = 'scale-down-horizontal-center',
  'scaleDownHorizontalLeft' = 'scale-down-horizontal-left',
  'scaleDownHorizontalRight' = 'scale-down-horizontal-right',
  'scaleDownVerticalCenter' = 'scale-down-vertical-center',
  'scaleDownVerticalTop' = 'scale-down-vertical-top',
  'scaleDownVerticalBottom' = 'scale-down-vertical-bottom',
  // ROTATE
  'rotateCenter' = 'rotate-center',
  'rotateTop' = 'rotate-top',
  'rotateBottom' = 'rotate-bottom',
  'rotateRight' = 'rotate-right',
  'rotateLeft' = 'rotate-left',
  'rotateTopRight' = 'rotate-top-right',
  'rotateTopLeft' = 'rotate-top-left',
  'rotateBottomLeft' = 'rotate-bottom-left',
  'rotateBottomRight' = 'rotate-bottom-right',
  'rotateHorizontalCenter' = 'rotate-horizontal-center',
  'rotateHorizontalTop' = 'rotate-horizontal-top',
  'rotateHorizontalBottom' = 'rotate-horizontal-bottom',
  'rotateVerticalCenter' = 'rotate-vertical-center',
  'rotateVerticalLeft' = 'rotate-vertical-left',
  'rotateVerticalRight' = 'rotate-vertical-right',
  'rotateDiagonalRight' = 'rotate-diagonal-right',
  'rotateDiagonalLeft' = 'rotate-diagonal-left',
  'rotateDiagonalTopRight' = 'rotate-diagonal-top-right',
  'rotateDiagonalTopLeft' = 'rotate-diagonal-top-left',
  'rotateDiagonalBottomLeft' = 'rotate-diagonal-bottom-left',
  'rotateDiagonalBottomRight' = 'rotate-diagonal-bottom-right',
  // ROTATE SCALE UP
  'rotateScaleUp' = 'rotate-scale-up',
  'rotateScaleDown' = 'rotate-scale-down',
  'rotateScaleUpHorizontal' = 'rotate-scale-up-horizontal',
  'rotateScaleDownHorizontal' = 'rotate-scale-down-horizontal',
  'rotateScaleUpVertical' = 'rotate-scale-up-vertical',
  'rotateScaleDownVertical' = 'rotate-scale-down-vertical',
  'rotateScaleUpDiagonalLeft' = 'rotate-scale-up-diagonal-left',
  'rotateScaleDownDiagonalLeft' = 'rotate-scale-down-diagonal-left',
  'rotateScaleDownDiagonalRight' = 'rotate-scale-down-diagonal-right',
  // SWING
  'swingTop' = 'swing-top',
  'swingBottom' = 'swing-bottom',
  'swingRight' = 'swing-right',
  'swingLeft' = 'swing-left',
  'swingTopRight' = 'swing-top-right',
  'swingTopLeft' = 'swing-top-left',
  'swingBottomLeft' = 'swing-bottom-left',
  'swingBottomRight' = 'swing-bottom-right',
  // slide
  'slideTop' = 'slide-top',
  'slideBottom' = 'slide-bottom',
  'slideLeft' = 'slide-left',
  'slideRight' = 'slide-right',
  'slideTopRight' = 'slide-top-right',
  'slideTopLeft' = 'slide-top-left',
  'slideBottomRight' = 'slide-bottom-right',
  'slideBottomLeft' = 'slide-bottom-left',
  'slideRotateHorizontalTop' = 'slide-rotate-horizontal-top',
  'slideRotateHorizontalBottom' = 'slide-rotate-horizontal-bottom',
  'slideRotateVerticalLeft' = 'slide-rotate-vertical-left',
  'slideRotateVerticalRight' = 'slide-rotate-vertical-right',
  // shadow
  'shadowDropCenter' = 'shadow-drop-center',
  'shadowDropTop' = 'shadow-drop-top',
  'shadowDropRight' = 'shadow-drop-right',
  'shadowDropBottom' = 'shadow-drop-bottom',
  'shadowDropLeft' = 'shadow-drop-left',
  'shadowDropLeftRight' = 'shadow-drop-left-right',
  'shadowDropTopBottom' = 'shadow-drop-top-bottom',
  'shadowDropTopRight' = 'shadow-drop-top-right',
  'shadowDropBottomRight' = 'shadow-drop-bottom-right',
  'shadowDropBottomLeft' = 'shadow-drop-bottom-left',
  'shadowDropTopLeft' = 'shadow-drop-top-left',
  'shadowPopTopRight' = 'shadow-pop-top-right',
  'shadowPopBottomRight' = 'shadow-pop-bottom-right',
  'shadowPopBottomLeft' = 'shadow-pop-bottom-left',
  'shadowPopTopLeft' = 'shadow-pop-top-left',
  'shadowInsetCenter' = 'shadow-inset-center',
  'shadowInsetTop' = 'shadow-inset-top',
  'shadowInsetRight' = 'shadow-inset-right',
  'shadowInsetBottom' = 'shadow-inset-bottom',
  'shadowInsetLeft' = 'shadow-inset-left',
  'shadowInsetTopRight' = 'shadow-inset-top-right',
  'shadowInsetBottomRight' = 'shadow-inset-bottom-right',
  'shadowInsetBottomLeft' = 'shadow-inset-bottom-left',
  'shadowInsetTopLeft' = 'shadow-inset-top-left',
  // blur
  'blurIn' = 'blur-in',
  'blurInExpand' = 'blur-in-expand',
  'blurOut' = 'blur-out',
  'blurOutExpand' = 'blur-out-expand',
  'blurOutContract' = 'blur-out-contract',
  // special
  'vibrate' = 'vibrate',
  'flicker' = 'flicker',
  'shakeHorizontal' = 'shake-horizontal',
  'shakeVertical' = 'shake-vertical',
  'shakeLeftRight' = 'shake-left-right',
  'shakeRight' = 'shake-right',
  'shakeLeft' = 'shake-left',
  'jelloHorizontal' = 'jello-horizontal',
  'jelloVertical' = 'jello-vertical',
  'jelloDiagonal' = 'jello-diagonal',
  'wobbleHorizontalBottom' = 'wobble-horizontal-bottom',
  'wobbleHorizontalTop' = 'wobble-horizontal-top',
  'wobbleVerticalLeft' = 'wobble-vertical-left',
  'wobbleVerticalRight' = 'wobble-vertical-right',
  'bounceTop' = 'bounce-top',
  'bounceBottom' = 'bounce-bottom',
  'bounceLeft' = 'bounce-left',
  'bounceRight' = 'bounce-right',
}
